### PR TITLE
Justinbarry/ch14334/built in augur app updating feature

### PR DESCRIPTION
**Pull request by justinbarry**
https://app.clubhouse.io/augur/story/14334/built-in-augur-app-updating-feature

### CODE REVIEW

**Comment by bthaile** [comment]
So steps on how to test this would really help out. 

also getting 

```
Error: Error: ENOENT: no such file or directory, open '/Users/bthaile/gitrepos/augur-app/dev-app-update.yml'
    at /Users/bthaile/gi
```

looks like a file was missed?

**Comment by justinbarry** [comment]
@bthaile Fixed.

**Comment by justinbarry** [comment]
I should probably get you some instructions on how to test this.....

**Comment by justinbarry** [comment]
1 . Run `npm run minio:spin-up`
2. Adjust version in package.json to a proper semver value. (e.g. 1.4.0)
3. Run `npm run publish:local`
4. Adjust version to previous version. (e.g. 1.3.0)
5. Run `npm run make:local`
6. Open dist/mac/Augur.app (This is mac specific)

Should see a popup notifying you of a new version.

**Comment by bthaile** [comment]
percentages look strange

screen shot 2018-08-13 at 1 25 23 pm

**Pull request merged**
